export type Unit = "reps" | "sec" | "m" | "steps" | "min";

export interface Exercise {
  id: string;
  name: string;
  cat: "strength" | "cardio" | "mobility";
  muscle: string;
  sets: number;
  reps: number;
  note?: string;
  unit?: Unit;
}

export interface ProgramExercise {
  exId: string;
  sets: number;
  reps: number;
}

export interface ProgramDay {
  label: string;
  focus: string;
  exercises: ProgramExercise[];
}

export interface Program {
  id: string;
  name: string;
  desc: string;
  days: ProgramDay[];
}

export interface SessionLog {
  date: string;
  programId: string;
  dayLabel: string;
  focus: string;
  exCount: number;
}

export interface Goal {
  targetWeight: string;
  weeklyTarget: number;
  notes: string;
  startDate: string;
}

export interface Note {
  title: string;
  body: string;
}

export interface Pose {
  id: string;
  name: string;
  sanskrit: string;
  category: string;
  focus: string;
  difficulty: "Beginner" | "Intermediate" | "Advanced";
  hold: number;
  shape: string;
  seq?: number | null;
  cue: string;
}

export interface WorkoutState {
  exercises: Exercise[];
  programs: Program[];
  activeProgramId: string | null;
  activeDayIndex: number;
  logs: SessionLog[];
  goal: Goal;
  myNotes: Note[];
  checks: Record<string, Record<number, boolean>>;
  videoUrl: string;
}

export function uid(): string {
  return Math.random().toString(36).slice(2, 10);
}

export function seedExercises(): Exercise[] {
  return [
    {
      id: "bw-squat",
      name: "Bodyweight Squat",
      cat: "strength",
      muscle: "Legs",
      sets: 3,
      reps: 15,
      unit: "reps",
      note: "Feet shoulder-width, toes slightly out, chest up. Add dumbbells once easy.",
    },
    {
      id: "glute-bridge",
      name: "Glute Bridge",
      cat: "strength",
      muscle: "Glutes",
      sets: 3,
      reps: 15,
      unit: "reps",
      note: "Feet hip-width, drive through heels, squeeze glutes at top.",
    },
    {
      id: "walk-lunge",
      name: "Walking Lunge",
      cat: "strength",
      muscle: "Legs",
      sets: 3,
      reps: 10,
      unit: "reps",
      note: "Per leg. Shoulder-width stance, front knee at 90 degrees. Bodyweight first.",
    },
    {
      id: "calf-raise",
      name: "Standing Calf Raise",
      cat: "strength",
      muscle: "Calves",
      sets: 3,
      reps: 20,
      unit: "reps",
      note: "Feet hip-width, rise slowly on toes, lower controlled.",
    },
    {
      id: "wall-sit",
      name: "Wall Sit",
      cat: "strength",
      muscle: "Legs",
      sets: 3,
      reps: 25,
      unit: "sec",
      note: "Seconds. Back flat on wall, thighs parallel to floor.",
    },
    {
      id: "incline-pushup",
      name: "Incline Push-Up",
      cat: "strength",
      muscle: "Chest",
      sets: 3,
      reps: 10,
      unit: "reps",
      note: "Hands shoulder-width, body in straight line. Elevate hands on bench/couch.",
    },
    {
      id: "db-row",
      name: "Dumbbell Row",
      cat: "strength",
      muscle: "Back",
      sets: 3,
      reps: 12,
      unit: "reps",
      note: "Per arm. Hinge at hip, back flat, pull dumbbell to hip. Start 3-4kg.",
    },
    {
      id: "db-shoulder-press",
      name: "Dumbbell Shoulder Press",
      cat: "strength",
      muscle: "Shoulders",
      sets: 3,
      reps: 10,
      unit: "reps",
      note: "Feet hip-width, palms forward, press overhead. Start 2-3kg.",
    },
    {
      id: "band-pullapart",
      name: "Band Pull-Apart",
      cat: "strength",
      muscle: "Back",
      sets: 3,
      reps: 15,
      unit: "reps",
      note: "Arms straight in front, pull band apart across chest, squeeze shoulder blades.",
    },
    {
      id: "bicep-curl",
      name: "Bicep Curl",
      cat: "strength",
      muscle: "Arms",
      sets: 3,
      reps: 12,
      unit: "reps",
      note: "Feet hip-width, elbows pinned to ribs. Start 2-3kg.",
    },
    {
      id: "walk",
      name: "Brisk Walk / Easy Cycle",
      cat: "cardio",
      muscle: "Full Body",
      sets: 1,
      reps: 1,
      unit: "min",
      note: "20-25 min. Moderate pace, maintain upright posture.",
    },
    {
      id: "plank",
      name: "Plank",
      cat: "strength",
      muscle: "Core",
      sets: 3,
      reps: 25,
      unit: "sec",
      note: "Seconds. Forearms on floor, body in straight line, core braced.",
    },
    {
      id: "dead-bug",
      name: "Dead Bug",
      cat: "strength",
      muscle: "Core",
      sets: 3,
      reps: 10,
      unit: "reps",
      note: "Per side. Lower back flat on floor, extend opposite arm and leg.",
    },
    {
      id: "bird-dog",
      name: "Bird Dog",
      cat: "strength",
      muscle: "Core",
      sets: 3,
      reps: 10,
      unit: "reps",
      note: "Per side. Tabletop position, extend opposite arm and leg simultaneously.",
    },
    {
      id: "goblet-squat",
      name: "Goblet Squat",
      cat: "strength",
      muscle: "Legs",
      sets: 3,
      reps: 12,
      unit: "reps",
      note: "Feet shoulder-width, hold weight at chest, elbows between knees at bottom. Start 4-6kg.",
    },
    {
      id: "db-deadlift",
      name: "Dumbbell Deadlift",
      cat: "strength",
      muscle: "Legs",
      sets: 3,
      reps: 10,
      unit: "reps",
      note: "Hip-width stance, soft knees, hinge at hips. Light weight, focus hip hinge.",
    },
    {
      id: "side-plank",
      name: "Side Plank",
      cat: "strength",
      muscle: "Core",
      sets: 2,
      reps: 18,
      unit: "sec",
      note: "Seconds, per side. Stack feet, lift hips, top hand on hip or overhead.",
    },
    {
      id: "hiit-circuit",
      name: "Bodyweight HIIT Circuit",
      cat: "cardio",
      muscle: "Full Body",
      sets: 8,
      reps: 30,
      unit: "sec",
      note: "30s work / 30s rest. Rotate through jumping jacks, high knees, squat jumps, mountain climbers.",
    },
    {
      id: "kb-swing",
      name: "Kettlebell Swing",
      cat: "strength",
      muscle: "Glutes",
      sets: 4,
      reps: 15,
      unit: "reps",
      note: "Feet wider than hip-width, hinge at hips, swing kettlebell to chest height.",
    },
    {
      id: "box-stepup",
      name: "Box Step-Up",
      cat: "strength",
      muscle: "Legs",
      sets: 3,
      reps: 12,
      unit: "reps",
      note: "Per leg. Foot fully on box, drive through heel, stand tall at top.",
    },
    {
      id: "hip-thrust",
      name: "Hip Thrust",
      cat: "strength",
      muscle: "Glutes",
      sets: 4,
      reps: 15,
      unit: "reps",
      note: "Shoulders on bench, feet hip-width, drive hips up, squeeze glutes at top.",
    },
    {
      id: "lateral-band-walk",
      name: "Lateral Band Walk",
      cat: "strength",
      muscle: "Glutes",
      sets: 3,
      reps: 20,
      unit: "steps",
      note: "Steps. Band above knees, half-squat position, step sideways maintaining tension.",
    },
    {
      id: "standard-pushup",
      name: "Standard Push-Up",
      cat: "strength",
      muscle: "Chest",
      sets: 3,
      reps: 12,
      unit: "reps",
      note: "Hands slightly wider than shoulder-width, body in straight line, lower chest to floor.",
    },
    {
      id: "diamond-pushup",
      name: "Diamond Push-Up",
      cat: "strength",
      muscle: "Triceps",
      sets: 3,
      reps: 10,
      unit: "reps",
      note: "Hands together under chest forming diamond shape, elbows track close to body.",
    },
    {
      id: "decline-pushup",
      name: "Decline Push-Up",
      cat: "strength",
      muscle: "Chest",
      sets: 3,
      reps: 10,
      unit: "reps",
      note: "Feet elevated on bench/couch, hands shoulder-width, body in straight line.",
    },
    {
      id: "romanian-deadlift",
      name: "Romanian Deadlift",
      cat: "strength",
      muscle: "Hamstrings",
      sets: 3,
      reps: 12,
      unit: "reps",
      note: "Hip-width stance, soft knees, hinge at hips, slight bend in knees throughout.",
    },
    {
      id: "bulgarian-squat",
      name: "Bulgarian Split Squat",
      cat: "strength",
      muscle: "Legs",
      sets: 3,
      reps: 10,
      unit: "reps",
      note: "Per leg. Rear foot elevated on bench, front knee at 90 degrees, torso upright.",
    },
    {
      id: "reverse-lunge",
      name: "Reverse Lunge",
      cat: "strength",
      muscle: "Legs",
      sets: 3,
      reps: 10,
      unit: "reps",
      note: "Per leg. Step back into lunge, both knees at 90 degrees, keep torso upright.",
    },
    {
      id: "hamstring-slider",
      name: "Hamstring Curl (Sliding)",
      cat: "strength",
      muscle: "Hamstrings",
      sets: 3,
      reps: 12,
      unit: "reps",
      note: "Lying on back, heels on towel, lift hips, slide heels toward glutes.",
    },
    {
      id: "tricep-dip",
      name: "Tricep Dip",
      cat: "strength",
      muscle: "Triceps",
      sets: 3,
      reps: 12,
      unit: "reps",
      note: "Hands on bench behind, fingers forward, lower body with elbows tracking back.",
    },
    {
      id: "hammer-curl",
      name: "Hammer Curl",
      cat: "strength",
      muscle: "Arms",
      sets: 3,
      reps: 12,
      unit: "reps",
      note: "Neutral grip (palms facing each other), per arm. Start 2-3kg.",
    },
    {
      id: "lateral-raise",
      name: "Lateral Raise",
      cat: "strength",
      muscle: "Shoulders",
      sets: 3,
      reps: 12,
      unit: "reps",
      note: "Light weight, slight forward lean, raise dumbbells to shoulder height, control descent.",
    },
    {
      id: "face-pull",
      name: "Face Pull",
      cat: "strength",
      muscle: "Shoulders",
      sets: 3,
      reps: 15,
      unit: "reps",
      note: "Band or cable at face height, pull toward face, squeeze shoulder blades, rotate hands.",
    },
    {
      id: "hollow-hold",
      name: "Hollow Hold",
      cat: "strength",
      muscle: "Core",
      sets: 3,
      reps: 20,
      unit: "sec",
      note: "Seconds. Lying on back, press lower back into floor, lift shoulders and legs off floor.",
    },
    {
      id: "leg-raise",
      name: "Leg Raise",
      cat: "strength",
      muscle: "Core",
      sets: 3,
      reps: 12,
      unit: "reps",
      note: "Lying on back, legs straight, raise to 90 degrees then lower slowly without arching back.",
    },
    {
      id: "russian-twist",
      name: "Russian Twist",
      cat: "strength",
      muscle: "Core",
      sets: 3,
      reps: 14,
      unit: "reps",
      note: "Per side. Seated, lean back slightly, rotate torso side to side with or without weight.",
    },
    {
      id: "pullup",
      name: "Pull-Up / Lat Pulldown",
      cat: "strength",
      muscle: "Back",
      sets: 3,
      reps: 8,
      unit: "reps",
      note: "Overhand grip, shoulder-width apart, pull chin to bar or bar to upper chest.",
    },
    {
      id: "jumping-jacks",
      name: "Jumping Jacks",
      cat: "cardio",
      muscle: "Full Body",
      sets: 3,
      reps: 30,
      unit: "sec",
      note: "Seconds. Land softly on balls of feet, arms sweep overhead in rhythm.",
    },
    {
      id: "mountain-climbers",
      name: "Mountain Climbers",
      cat: "cardio",
      muscle: "Full Body",
      sets: 3,
      reps: 30,
      unit: "sec",
      note: "Seconds. Plank position, drive knees to chest alternately, keep hips level.",
    },
    {
      id: "burpees",
      name: "Burpees",
      cat: "cardio",
      muscle: "Full Body",
      sets: 3,
      reps: 10,
      unit: "reps",
      note: "Squat down, kick feet back to plank, do a push-up, jump feet forward, explode up.",
    },
    {
      id: "high-knees",
      name: "High Knees",
      cat: "cardio",
      muscle: "Legs",
      sets: 3,
      reps: 30,
      unit: "sec",
      note: "Seconds. Drive knees up to waist height, pump arms, land softly.",
    },
    {
      id: "jump-rope",
      name: "Jump Rope",
      cat: "cardio",
      muscle: "Full Body",
      sets: 3,
      reps: 60,
      unit: "sec",
      note: "Seconds. Light bounce on balls of feet, wrists rotate rope, keep elbows close.",
    },
    {
      id: "rowing-machine",
      name: "Rowing Machine",
      cat: "cardio",
      muscle: "Full Body",
      sets: 3,
      reps: 500,
      unit: "m",
      note: "Meters. Legs drive first, then pull arms, reverse order on recovery.",
    },
    {
      id: "sprint-intervals",
      name: "Sprint Intervals",
      cat: "cardio",
      muscle: "Legs",
      sets: 8,
      reps: 30,
      unit: "sec",
      note: "Seconds. Max effort sprint, 30s active recovery between.",
    },
    {
      id: "yoga-flow",
      name: "Gentle Yoga Flow",
      cat: "mobility",
      muscle: "Full Body",
      sets: 1,
      reps: 1,
      unit: "min",
      note: "15-20 min. See Yoga tab.",
    },
  ];
}

export function seedPrograms(): Program[] {
  return [
    {
      id: "magnus-recomp",
      name: "Magnus Method — 7 Day Recomposition",
      desc: "Beginner-friendly strength-first split with light cardio, built to lose fat and build muscle at the same time.",
      days: [
        {
          label: "Day 1",
          focus: "Lower Body Strength",
          exercises: [
            { exId: "bw-squat", sets: 3, reps: 15 },
            { exId: "glute-bridge", sets: 3, reps: 15 },
            { exId: "walk-lunge", sets: 3, reps: 10 },
            { exId: "calf-raise", sets: 3, reps: 20 },
            { exId: "wall-sit", sets: 3, reps: 25 },
          ],
        },
        {
          label: "Day 2",
          focus: "Upper Body Strength",
          exercises: [
            { exId: "incline-pushup", sets: 3, reps: 10 },
            { exId: "db-row", sets: 3, reps: 12 },
            { exId: "db-shoulder-press", sets: 3, reps: 10 },
            { exId: "band-pullapart", sets: 3, reps: 15 },
            { exId: "bicep-curl", sets: 3, reps: 12 },
          ],
        },
        {
          label: "Day 3",
          focus: "Light Cardio + Core",
          exercises: [
            { exId: "walk", sets: 1, reps: 1 },
            { exId: "plank", sets: 3, reps: 25 },
            { exId: "dead-bug", sets: 3, reps: 10 },
            { exId: "bird-dog", sets: 3, reps: 10 },
          ],
        },
        { label: "Day 4", focus: "Rest", exercises: [] },
        {
          label: "Day 5",
          focus: "Full Body Strength",
          exercises: [
            { exId: "goblet-squat", sets: 3, reps: 12 },
            { exId: "db-deadlift", sets: 3, reps: 10 },
            { exId: "incline-pushup", sets: 3, reps: 10 },
            { exId: "db-row", sets: 3, reps: 15 },
            { exId: "side-plank", sets: 2, reps: 18 },
          ],
        },
        {
          label: "Day 6",
          focus: "Short HIIT (15-20min)",
          exercises: [{ exId: "hiit-circuit", sets: 8, reps: 30 }],
        },
        {
          label: "Day 7",
          focus: "Rest / Mobility",
          exercises: [{ exId: "yoga-flow", sets: 1, reps: 1 }],
        },
      ],
    },
    {
      id: "glute-leg-focus",
      name: "Glute & Leg Focus",
      desc: "Lower body emphasis with upper body maintenance. Build strong glutes and legs with two lower days, one upper day, and a HIIT finisher.",
      days: [
        {
          label: "Day 1",
          focus: "Lower Strength",
          exercises: [
            { exId: "goblet-squat", sets: 3, reps: 12 },
            { exId: "hip-thrust", sets: 4, reps: 15 },
            { exId: "bulgarian-squat", sets: 3, reps: 10 },
            { exId: "calf-raise", sets: 3, reps: 20 },
            { exId: "reverse-lunge", sets: 3, reps: 10 },
          ],
        },
        {
          label: "Day 2",
          focus: "Upper Push/Pull",
          exercises: [
            { exId: "standard-pushup", sets: 3, reps: 12 },
            { exId: "db-row", sets: 3, reps: 12 },
            { exId: "db-shoulder-press", sets: 3, reps: 10 },
            { exId: "band-pullapart", sets: 3, reps: 15 },
            { exId: "tricep-dip", sets: 3, reps: 12 },
          ],
        },
        {
          label: "Day 3",
          focus: "Glutes + Core",
          exercises: [
            { exId: "glute-bridge", sets: 3, reps: 15 },
            { exId: "kb-swing", sets: 4, reps: 15 },
            { exId: "lateral-band-walk", sets: 3, reps: 20 },
            { exId: "dead-bug", sets: 3, reps: 10 },
            { exId: "hollow-hold", sets: 3, reps: 20 },
          ],
        },
        {
          label: "Day 4",
          focus: "Active Recovery",
          exercises: [{ exId: "walk", sets: 1, reps: 1 }],
        },
        {
          label: "Day 5",
          focus: "Lower Strength V2",
          exercises: [
            { exId: "bw-squat", sets: 3, reps: 15 },
            { exId: "walk-lunge", sets: 3, reps: 10 },
            { exId: "romanian-deadlift", sets: 3, reps: 12 },
            { exId: "box-stepup", sets: 3, reps: 12 },
            { exId: "wall-sit", sets: 3, reps: 25 },
          ],
        },
        {
          label: "Day 6",
          focus: "HIIT Cardio + Core",
          exercises: [
            { exId: "burpees", sets: 3, reps: 10 },
            { exId: "mountain-climbers", sets: 3, reps: 30 },
            { exId: "high-knees", sets: 3, reps: 30 },
            { exId: "plank", sets: 3, reps: 25 },
            { exId: "russian-twist", sets: 3, reps: 14 },
          ],
        },
        {
          label: "Day 7",
          focus: "Rest / Mobility",
          exercises: [{ exId: "yoga-flow", sets: 1, reps: 1 }],
        },
      ],
    },
    {
      id: "upper-lower-split",
      name: "Upper/Lower Split",
      desc: "Classic 4-day upper/lower split with recovery days. Balanced strength development across all major muscle groups.",
      days: [
        {
          label: "Day 1",
          focus: "Lower Quad Focus",
          exercises: [
            { exId: "goblet-squat", sets: 3, reps: 12 },
            { exId: "bulgarian-squat", sets: 3, reps: 10 },
            { exId: "box-stepup", sets: 3, reps: 12 },
            { exId: "leg-raise", sets: 3, reps: 12 },
          ],
        },
        {
          label: "Day 2",
          focus: "Upper Push",
          exercises: [
            { exId: "diamond-pushup", sets: 3, reps: 10 },
            { exId: "db-shoulder-press", sets: 3, reps: 10 },
            { exId: "lateral-raise", sets: 3, reps: 12 },
            { exId: "tricep-dip", sets: 3, reps: 12 },
            { exId: "plank", sets: 3, reps: 25 },
          ],
        },
        {
          label: "Day 3",
          focus: "Lower Posterior",
          exercises: [
            { exId: "romanian-deadlift", sets: 3, reps: 12 },
            { exId: "hip-thrust", sets: 4, reps: 15 },
            { exId: "hamstring-slider", sets: 3, reps: 12 },
            { exId: "bird-dog", sets: 3, reps: 10 },
          ],
        },
        {
          label: "Day 4",
          focus: "Upper Pull",
          exercises: [
            { exId: "pullup", sets: 3, reps: 8 },
            { exId: "db-row", sets: 3, reps: 12 },
            { exId: "hammer-curl", sets: 3, reps: 12 },
            { exId: "face-pull", sets: 3, reps: 15 },
            { exId: "side-plank", sets: 2, reps: 18 },
          ],
        },
        { label: "Day 5", focus: "Rest", exercises: [] },
        {
          label: "Day 6",
          focus: "Full Body Conditioning",
          exercises: [
            { exId: "kb-swing", sets: 4, reps: 15 },
            { exId: "burpees", sets: 3, reps: 10 },
            { exId: "walk-lunge", sets: 3, reps: 10 },
            { exId: "standard-pushup", sets: 3, reps: 12 },
            { exId: "hollow-hold", sets: 3, reps: 20 },
          ],
        },
        {
          label: "Day 7",
          focus: "Rest / Mobility",
          exercises: [{ exId: "yoga-flow", sets: 1, reps: 1 }],
        },
      ],
    },
    {
      id: "fat-loss-ignite",
      name: "Fat Loss Ignite",
      desc: "Five days of strength and HIIT for maximum calorie burn. Strength 3x/week and HIIT 2x/week with active recovery.",
      days: [
        {
          label: "Day 1",
          focus: "Full Body Strength",
          exercises: [
            { exId: "goblet-squat", sets: 3, reps: 12 },
            { exId: "incline-pushup", sets: 3, reps: 10 },
            { exId: "db-row", sets: 3, reps: 12 },
            { exId: "bicep-curl", sets: 3, reps: 12 },
            { exId: "plank", sets: 3, reps: 25 },
          ],
        },
        {
          label: "Day 2",
          focus: "HIIT Cardio",
          exercises: [
            { exId: "burpees", sets: 3, reps: 10 },
            { exId: "mountain-climbers", sets: 3, reps: 30 },
            { exId: "high-knees", sets: 3, reps: 30 },
            { exId: "jumping-jacks", sets: 3, reps: 30 },
            { exId: "sprint-intervals", sets: 8, reps: 30 },
          ],
        },
        {
          label: "Day 3",
          focus: "Lower Strength",
          exercises: [
            { exId: "romanian-deadlift", sets: 3, reps: 12 },
            { exId: "walk-lunge", sets: 3, reps: 10 },
            { exId: "glute-bridge", sets: 3, reps: 15 },
            { exId: "lateral-band-walk", sets: 3, reps: 20 },
          ],
        },
        {
          label: "Day 4",
          focus: "HIIT Cardio",
          exercises: [
            { exId: "jump-rope", sets: 3, reps: 60 },
            { exId: "kb-swing", sets: 4, reps: 15 },
            { exId: "rowing-machine", sets: 3, reps: 500 },
            { exId: "hiit-circuit", sets: 8, reps: 30 },
          ],
        },
        {
          label: "Day 5",
          focus: "Full Body Strength",
          exercises: [
            { exId: "standard-pushup", sets: 3, reps: 12 },
            { exId: "pullup", sets: 3, reps: 8 },
            { exId: "db-deadlift", sets: 3, reps: 10 },
            { exId: "dead-bug", sets: 3, reps: 10 },
            { exId: "russian-twist", sets: 3, reps: 14 },
          ],
        },
        {
          label: "Day 6",
          focus: "Active Recovery",
          exercises: [{ exId: "walk", sets: 1, reps: 1 }],
        },
        {
          label: "Day 7",
          focus: "Rest / Yoga",
          exercises: [{ exId: "yoga-flow", sets: 1, reps: 1 }],
        },
      ],
    },
    {
      id: "bodyweight-basics",
      name: "Bodyweight Basics",
      desc: "Zero equipment needed. Perfect for home workouts, travel, or beginners building foundational strength.",
      days: [
        {
          label: "Day 1",
          focus: "Lower Body",
          exercises: [
            { exId: "bw-squat", sets: 3, reps: 15 },
            { exId: "reverse-lunge", sets: 3, reps: 10 },
            { exId: "glute-bridge", sets: 3, reps: 15 },
            { exId: "calf-raise", sets: 3, reps: 20 },
            { exId: "wall-sit", sets: 3, reps: 25 },
          ],
        },
        {
          label: "Day 2",
          focus: "Upper + Core",
          exercises: [
            { exId: "standard-pushup", sets: 3, reps: 12 },
            { exId: "tricep-dip", sets: 3, reps: 12 },
            { exId: "plank", sets: 3, reps: 25 },
            { exId: "bird-dog", sets: 3, reps: 10 },
            { exId: "hollow-hold", sets: 3, reps: 20 },
          ],
        },
        {
          label: "Day 3",
          focus: "Full Body",
          exercises: [
            { exId: "walk-lunge", sets: 3, reps: 10 },
            { exId: "incline-pushup", sets: 3, reps: 10 },
            { exId: "mountain-climbers", sets: 3, reps: 30 },
            { exId: "plank", sets: 3, reps: 25 },
            { exId: "burpees", sets: 3, reps: 10 },
          ],
        },
        { label: "Day 4", focus: "Rest", exercises: [] },
        {
          label: "Day 5",
          focus: "Lower Body V2",
          exercises: [
            { exId: "glute-bridge", sets: 3, reps: 15 },
            { exId: "bw-squat", sets: 3, reps: 15 },
            { exId: "lateral-band-walk", sets: 3, reps: 20 },
            { exId: "wall-sit", sets: 3, reps: 25 },
            { exId: "leg-raise", sets: 3, reps: 12 },
          ],
        },
        {
          label: "Day 6",
          focus: "Core + Cardio",
          exercises: [
            { exId: "dead-bug", sets: 3, reps: 10 },
            { exId: "russian-twist", sets: 3, reps: 14 },
            { exId: "side-plank", sets: 2, reps: 18 },
            { exId: "jumping-jacks", sets: 3, reps: 30 },
            { exId: "high-knees", sets: 3, reps: 30 },
          ],
        },
        {
          label: "Day 7",
          focus: "Rest / Yoga",
          exercises: [{ exId: "yoga-flow", sets: 1, reps: 1 }],
        },
      ],
    },
    {
      id: "core-posture",
      name: "Core & Posture",
      desc: "Build a strong core and better posture. Complements yoga practice with focused core work and back-strengthening exercises.",
      days: [
        {
          label: "Day 1",
          focus: "Core Strength",
          exercises: [
            { exId: "plank", sets: 3, reps: 25 },
            { exId: "dead-bug", sets: 3, reps: 10 },
            { exId: "hollow-hold", sets: 3, reps: 20 },
            { exId: "side-plank", sets: 2, reps: 18 },
            { exId: "leg-raise", sets: 3, reps: 12 },
          ],
        },
        {
          label: "Day 2",
          focus: "Posture + Back",
          exercises: [
            { exId: "band-pullapart", sets: 3, reps: 15 },
            { exId: "face-pull", sets: 3, reps: 15 },
            { exId: "bird-dog", sets: 3, reps: 10 },
            { exId: "db-deadlift", sets: 3, reps: 10 },
            { exId: "db-row", sets: 3, reps: 12 },
          ],
        },
        {
          label: "Day 3",
          focus: "Full Body Flow",
          exercises: [
            { exId: "yoga-flow", sets: 1, reps: 1 },
            { exId: "russian-twist", sets: 3, reps: 14 },
            { exId: "wall-sit", sets: 3, reps: 25 },
          ],
        },
        { label: "Day 4", focus: "Rest", exercises: [] },
        {
          label: "Day 5",
          focus: "Core Strength V2",
          exercises: [
            { exId: "plank", sets: 3, reps: 25 },
            { exId: "dead-bug", sets: 3, reps: 10 },
            { exId: "hollow-hold", sets: 3, reps: 20 },
            { exId: "russian-twist", sets: 3, reps: 14 },
            { exId: "leg-raise", sets: 3, reps: 12 },
          ],
        },
        {
          label: "Day 6",
          focus: "Cardio + Mobility",
          exercises: [
            { exId: "walk", sets: 1, reps: 1 },
            { exId: "jumping-jacks", sets: 3, reps: 30 },
            { exId: "bird-dog", sets: 3, reps: 10 },
            { exId: "yoga-flow", sets: 1, reps: 1 },
          ],
        },
        {
          label: "Day 7",
          focus: "Yoga / Full Body Stretch",
          exercises: [{ exId: "yoga-flow", sets: 1, reps: 1 }],
        },
      ],
    },
    {
      id: "tomb-raider",
      name: "Tomb Raider Training",
      desc: "Inspired by Magnus Lygdback's training for Alicia Vikander's Lara Croft. Functional, lean muscle, HIIT-heavy, full-body capability.",
      days: [
        {
          label: "Day 1",
          focus: "HIIT + Legs + Core",
          exercises: [
            { exId: "sprint-intervals", sets: 8, reps: 30 },
            { exId: "goblet-squat", sets: 3, reps: 12 },
            { exId: "walk-lunge", sets: 3, reps: 10 },
            { exId: "dead-bug", sets: 3, reps: 10 },
            { exId: "plank", sets: 3, reps: 25 },
          ],
        },
        {
          label: "Day 2",
          focus: "Cardio + Back + Shoulders",
          exercises: [
            { exId: "rowing-machine", sets: 3, reps: 500 },
            { exId: "pullup", sets: 3, reps: 8 },
            { exId: "db-row", sets: 3, reps: 12 },
            { exId: "db-shoulder-press", sets: 3, reps: 10 },
            { exId: "face-pull", sets: 3, reps: 15 },
          ],
        },
        {
          label: "Day 3",
          focus: "Mobility + Chest + Arms",
          exercises: [
            { exId: "yoga-flow", sets: 1, reps: 1 },
            { exId: "incline-pushup", sets: 3, reps: 10 },
            { exId: "standard-pushup", sets: 3, reps: 12 },
            { exId: "bicep-curl", sets: 3, reps: 12 },
            { exId: "tricep-dip", sets: 3, reps: 12 },
          ],
        },
        {
          label: "Day 4",
          focus: "HIIT + Legs + Core",
          exercises: [
            { exId: "burpees", sets: 3, reps: 10 },
            { exId: "bulgarian-squat", sets: 3, reps: 10 },
            { exId: "reverse-lunge", sets: 3, reps: 10 },
            { exId: "hollow-hold", sets: 3, reps: 20 },
            { exId: "russian-twist", sets: 3, reps: 14 },
          ],
        },
        {
          label: "Day 5",
          focus: "Cardio + Back + Shoulders",
          exercises: [
            { exId: "jump-rope", sets: 3, reps: 60 },
            { exId: "band-pullapart", sets: 3, reps: 15 },
            { exId: "hammer-curl", sets: 3, reps: 12 },
            { exId: "lateral-raise", sets: 3, reps: 12 },
            { exId: "side-plank", sets: 2, reps: 18 },
          ],
        },
        {
          label: "Day 6",
          focus: "Full Body Adventure",
          exercises: [
            { exId: "kb-swing", sets: 4, reps: 15 },
            { exId: "mountain-climbers", sets: 3, reps: 30 },
            { exId: "box-stepup", sets: 3, reps: 12 },
            { exId: "diamond-pushup", sets: 3, reps: 10 },
            { exId: "bird-dog", sets: 3, reps: 10 },
          ],
        },
        {
          label: "Day 7",
          focus: "Rest / Recovery",
          exercises: [{ exId: "yoga-flow", sets: 1, reps: 1 }],
        },
      ],
    },
  ];
}

export function seedState(): WorkoutState {
  return {
    exercises: seedExercises(),
    programs: seedPrograms(),
    activeProgramId: "magnus-recomp",
    activeDayIndex: 0,
    logs: [],
    goal: {
      targetWeight: "",
      weeklyTarget: 5,
      notes: "",
      startDate: new Date().toISOString().slice(0, 10),
    },
    myNotes: [],
    checks: {},
    videoUrl: "",
  };
}

export const SHAPES: Record<string, string> = {
  standing: `<path d="M45 15 L45 65 M45 28 L28 45 M45 28 L62 45 M45 65 L30 85 M45 65 L60 85" stroke="currentColor" stroke-width="3" fill="none" stroke-linecap="round"/><circle cx="45" cy="10" r="6" fill="currentColor"/>`,
  armsUp: `<path d="M45 22 L45 65 M45 28 L28 12 M45 28 L62 12 M45 65 L30 85 M45 65 L60 85" stroke="currentColor" stroke-width="3" fill="none" stroke-linecap="round"/><circle cx="45" cy="16" r="6" fill="currentColor"/>`,
  backArch: `<path d="M45 20 Q55 45 42 70 M45 26 L28 14 M45 26 L60 30 M42 70 L28 85 M42 70 L54 85" stroke="currentColor" stroke-width="3" fill="none" stroke-linecap="round"/><circle cx="46" cy="14" r="6" fill="currentColor"/>`,
  chair: `<path d="M45 20 L45 48 M45 48 L30 80 M45 48 L58 78 M45 25 L62 32" stroke="currentColor" stroke-width="3" fill="none" stroke-linecap="round"/><circle cx="45" cy="14" r="6" fill="currentColor"/>`,
  eagle: `<path d="M45 20 L45 55 M45 30 Q52 35 45 42 Q38 48 45 52 M45 55 Q52 65 45 75 Q38 82 46 85" stroke="currentColor" stroke-width="3" fill="none" stroke-linecap="round"/><circle cx="45" cy="14" r="6" fill="currentColor"/>`,
  standKneeUp: `<path d="M45 18 L45 55 M45 55 L30 85 M45 35 L62 25 M45 55 Q52 45 48 32" stroke="currentColor" stroke-width="3" fill="none" stroke-linecap="round"/><circle cx="45" cy="12" r="6" fill="currentColor"/>`,
  standingBow: `<path d="M45 22 Q52 42 40 60 M45 28 L62 15 M40 60 L52 82 M40 60 Q30 45 22 30" stroke="currentColor" stroke-width="3" fill="none" stroke-linecap="round"/><circle cx="46" cy="16" r="6" fill="currentColor"/>`,
  balanceStick: `<path d="M20 40 L70 40 M20 40 L12 55 M70 40 L82 30" stroke="currentColor" stroke-width="3" fill="none" stroke-linecap="round"/><circle cx="16" cy="44" r="6" fill="currentColor"/>`,
  straddleFold: `<path d="M45 25 L45 45 M45 45 L25 78 M45 45 L65 78 M45 30 L45 65" stroke="currentColor" stroke-width="3" fill="none" stroke-linecap="round"/><circle cx="45" cy="66" r="6" fill="currentColor"/>`,
  triangle: `<path d="M45 18 L30 80 M45 18 L62 55 M45 18 L20 26" stroke="currentColor" stroke-width="3" fill="none" stroke-linecap="round"/><circle cx="45" cy="12" r="6" fill="currentColor"/>`,
  tree: `<path d="M45 18 L45 70 M45 70 L28 82 M45 42 L30 42 M45 20 L30 8 M45 20 L60 8" stroke="currentColor" stroke-width="3" fill="none" stroke-linecap="round"/><circle cx="45" cy="12" r="6" fill="currentColor"/>`,
  toeStand: `<path d="M45 30 L45 55 M45 55 L38 78 M45 40 L60 35 M45 40 L30 48" stroke="currentColor" stroke-width="3" fill="none" stroke-linecap="round"/><circle cx="45" cy="24" r="6" fill="currentColor"/>`,
  seatedFold: `<path d="M20 75 L55 75 M20 75 Q40 55 55 30 M55 75 L60 60" stroke="currentColor" stroke-width="3" fill="none" stroke-linecap="round"/><circle cx="58" cy="26" r="6" fill="currentColor"/>`,
  windRemoving: `<path d="M25 55 Q45 40 55 55 M25 55 L15 62 M55 55 L65 62" stroke="currentColor" stroke-width="3" fill="none" stroke-linecap="round"/><circle cx="20" cy="50" r="6" fill="currentColor"/>`,
  cobra: `<path d="M15 68 Q45 35 78 62 M40 68 L36 80 M58 66 L62 80" stroke="currentColor" stroke-width="3" fill="none" stroke-linecap="round"/><circle cx="78" cy="56" r="6" fill="currentColor"/>`,
  locust: `<path d="M15 60 L60 55 Q70 45 78 30 M15 60 L20 74 M60 55 L58 70" stroke="currentColor" stroke-width="3" fill="none" stroke-linecap="round"/><circle cx="12" cy="58" r="6" fill="currentColor"/>`,
  fullLocust: `<path d="M20 65 Q45 68 55 50 Q65 32 75 20 M20 65 Q35 50 32 30" stroke="currentColor" stroke-width="3" fill="none" stroke-linecap="round"/><circle cx="14" cy="66" r="6" fill="currentColor"/>`,
  bowPose: `<path d="M30 60 Q45 30 65 45 Q60 65 40 70 Q28 72 30 60" stroke="currentColor" stroke-width="3" fill="none" stroke-linecap="round"/><circle cx="34" cy="55" r="6" fill="currentColor"/>`,
  kneelLeanBack: `<path d="M45 30 Q55 55 42 75 M45 75 L38 85 M45 75 L52 85 M45 35 L62 40" stroke="currentColor" stroke-width="3" fill="none" stroke-linecap="round"/><circle cx="45" cy="24" r="6" fill="currentColor"/>`,
  kneelForward: `<path d="M45 40 Q30 55 45 78 M45 40 L45 25 M45 78 L38 85 M45 78 L52 85" stroke="currentColor" stroke-width="3" fill="none" stroke-linecap="round"/><circle cx="46" cy="18" r="6" fill="currentColor"/>`,
  seatedTwist: `<path d="M45 30 L45 60 M45 60 L28 78 M45 60 L58 74 M45 36 L64 24 M45 36 L30 44" stroke="currentColor" stroke-width="3" fill="none" stroke-linecap="round"/><circle cx="45" cy="24" r="6" fill="currentColor"/>`,
  corpse: `<path d="M15 55 L78 55 M28 55 L20 68 M28 55 L24 42 M60 55 L68 68 M60 55 L64 42" stroke="currentColor" stroke-width="3" fill="none" stroke-linecap="round"/><circle cx="10" cy="54" r="6" fill="currentColor"/>`,
  downdog: `<path d="M18 72 L45 38 L72 72" stroke="currentColor" stroke-width="3" fill="none" stroke-linecap="round"/><circle cx="45" cy="32" r="6" fill="currentColor"/>`,
  updog: `<path d="M15 68 Q45 30 78 58 M40 66 L34 80" stroke="currentColor" stroke-width="3" fill="none" stroke-linecap="round"/><circle cx="78" cy="52" r="6" fill="currentColor"/>`,
  plank: `<path d="M15 55 L75 50 M15 55 L20 70 M75 50 L70 66" stroke="currentColor" stroke-width="3" fill="none" stroke-linecap="round"/><circle cx="12" cy="53" r="6" fill="currentColor"/>`,
  chaturanga: `<path d="M15 60 L75 60 M15 60 L22 70 M75 60 L68 70" stroke="currentColor" stroke-width="3" fill="none" stroke-linecap="round"/><circle cx="12" cy="58" r="6" fill="currentColor"/>`,
  pigeon: `<path d="M15 68 L48 60 L75 74 M48 60 L52 30" stroke="currentColor" stroke-width="3" fill="none" stroke-linecap="round"/><circle cx="54" cy="24" r="6" fill="currentColor"/>`,
  warrior1: `<path d="M45 20 L45 50 M45 50 L30 78 M45 50 L62 72 M45 26 L26 18 M45 26 L64 18" stroke="currentColor" stroke-width="3" fill="none" stroke-linecap="round"/><circle cx="45" cy="14" r="6" fill="currentColor"/>`,
  warrior2: `<path d="M45 20 L45 50 M45 50 L26 78 M45 50 L64 78 M45 28 L20 28 M45 28 L70 28" stroke="currentColor" stroke-width="3" fill="none" stroke-linecap="round"/><circle cx="45" cy="14" r="6" fill="currentColor"/>`,
  lunge: `<path d="M45 22 L45 50 M45 50 L26 82 M45 50 L60 70 M45 28 L60 15" stroke="currentColor" stroke-width="3" fill="none" stroke-linecap="round"/><circle cx="45" cy="16" r="6" fill="currentColor"/>`,
  bridge: `<path d="M15 62 L45 62 Q60 62 62 45 M15 62 L20 76" stroke="currentColor" stroke-width="3" fill="none" stroke-linecap="round"/><circle cx="10" cy="60" r="6" fill="currentColor"/>`,
  wheel: `<path d="M20 68 Q45 20 70 55 M20 68 L14 55 M70 55 L76 68" stroke="currentColor" stroke-width="3" fill="none" stroke-linecap="round"/><circle cx="42" cy="30" r="6" fill="currentColor"/>`,
  fish: `<path d="M15 60 Q40 60 50 45 Q56 35 62 20 M15 60 L20 74" stroke="currentColor" stroke-width="3" fill="none" stroke-linecap="round"/><circle cx="66" cy="16" r="6" fill="currentColor"/>`,
  butterfly: `<path d="M45 30 L45 55 M45 55 L28 62 M45 55 L62 62 M28 62 L45 68 M62 62 L45 68" stroke="currentColor" stroke-width="3" fill="none" stroke-linecap="round"/><circle cx="45" cy="24" r="6" fill="currentColor"/>`,
  recliningTwist: `<path d="M18 40 L60 40 M60 40 L72 60 M60 40 L72 22" stroke="currentColor" stroke-width="3" fill="none" stroke-linecap="round"/><circle cx="12" cy="40" r="6" fill="currentColor"/>`,
  happyBaby: `<path d="M45 55 L45 68 M45 55 L28 40 M45 55 L62 40 M28 40 L20 55 M62 40 L70 55" stroke="currentColor" stroke-width="3" fill="none" stroke-linecap="round"/><circle cx="45" cy="72" r="6" fill="currentColor"/>`,
  sidePlank: `<path d="M15 60 L75 45 M15 60 L20 74 M75 45 L80 30" stroke="currentColor" stroke-width="3" fill="none" stroke-linecap="round"/><circle cx="12" cy="58" r="6" fill="currentColor"/>`,
  childs: `<path d="M20 78 Q45 78 52 50 L64 32" stroke="currentColor" stroke-width="3" fill="none" stroke-linecap="round"/><circle cx="66" cy="27" r="6" fill="currentColor"/>`,
  catCow: `<path d="M15 55 Q45 35 78 55 M15 55 L20 70 M78 55 L72 70" stroke="currentColor" stroke-width="3" fill="none" stroke-linecap="round"/><circle cx="12" cy="53" r="6" fill="currentColor"/>`,
  forwardFold: `<path d="M45 20 L45 50 M45 20 L28 12 M45 20 L62 12 M45 50 L30 85 M45 50 L60 85 M45 25 L45 75" stroke="currentColor" stroke-width="3" fill="none" stroke-linecap="round"/><circle cx="45" cy="14" r="6" fill="currentColor"/>`,
  reverseWarrior: `<path d="M45 18 L30 80 M45 18 L62 50 M45 26 L62 15 M45 50 L74 70" stroke="currentColor" stroke-width="3" fill="none" stroke-linecap="round"/><circle cx="45" cy="12" r="6" fill="currentColor"/>`,
  shoulderStand: `<path d="M35 55 L58 55 M58 55 L62 42 M58 55 L65 66 M55 30 L55 15 M62 28 L62 12" stroke="currentColor" stroke-width="3" fill="none" stroke-linecap="round"/><circle cx="59" cy="8" r="6" fill="currentColor"/>`,
  plowPose: `<path d="M35 55 L58 55 M58 55 L62 42 M58 55 L65 66 M55 30 L40 15 M62 28 L45 12 M40 15 L45 18 M45 12 L50 18" stroke="currentColor" stroke-width="3" fill="none" stroke-linecap="round"/><circle cx="47" cy="8" r="6" fill="currentColor"/>`,
  bow: `<path d="M30 60 Q45 30 65 45 Q60 65 40 70 Q28 72 30 60" stroke="currentColor" stroke-width="3" fill="none" stroke-linecap="round"/><circle cx="34" cy="55" r="6" fill="currentColor"/>`,
  camel: `<path d="M45 30 Q55 55 42 75 M45 75 L38 85 M45 75 L52 85 M45 35 L62 40" stroke="currentColor" stroke-width="3" fill="none" stroke-linecap="round"/><circle cx="45" cy="24" r="6" fill="currentColor"/>`,
  fixedFirm: `<path d="M45 30 Q55 55 42 75 M45 75 L38 85 M45 75 L52 85 M45 35 L62 40" stroke="currentColor" stroke-width="3" fill="none" stroke-linecap="round"/><circle cx="45" cy="24" r="6" fill="currentColor"/>`,
  rabbit: `<path d="M45 40 Q30 55 45 78 M45 40 L45 25 M45 78 L38 85 M45 78 L52 85" stroke="currentColor" stroke-width="3" fill="none" stroke-linecap="round"/><circle cx="46" cy="18" r="6" fill="currentColor"/>`,
  headToKnee: `<path d="M20 75 L55 75 M20 75 Q40 55 55 30 M55 75 L60 60" stroke="currentColor" stroke-width="3" fill="none" stroke-linecap="round"/><circle cx="58" cy="26" r="6" fill="currentColor"/>`,
  spineTwist: `<path d="M45 30 L45 60 M45 60 L28 78 M45 60 L58 74 M45 36 L64 24 M45 36 L30 44" stroke="currentColor" stroke-width="3" fill="none" stroke-linecap="round"/><circle cx="45" cy="24" r="6" fill="currentColor"/>`,
  sideAngle: `<path d="M45 18 L28 70 M45 18 L62 50 M45 26 L20 30 M28 70 L62 60" stroke="currentColor" stroke-width="3" fill="none" stroke-linecap="round"/><circle cx="45" cy="12" r="6" fill="currentColor"/>`,
  sitUp: `<path d="M20 72 L45 35 L70 72 M45 35 L30 18 M45 35 L60 18" stroke="currentColor" stroke-width="3" fill="none" stroke-linecap="round"/><circle cx="45" cy="12" r="6" fill="currentColor"/>`,
};

export const POSES: Pose[] = [
  {
    name: "Standing Deep Breathing",
    id: "standing-deep-breathing",
    sanskrit: "Pranayama",
    category: "Standing",
    focus: "Lungs, warms the body",
    difficulty: "Beginner",
    hold: 30,
    shape: "armsUp",
    seq: 1,
    cue: "Fingers interlaced under the chin, inhale as elbows lift wide, exhale as elbows draw together. Sets the breath for the whole practice.",
  },
  {
    name: "Half Moon Pose",
    id: "half-moon",
    sanskrit: "Ardha Chandrasana",
    category: "Backbend",
    focus: "Spine, obliques, shoulders",
    difficulty: "Intermediate",
    hold: 20,
    shape: "backArch",
    seq: 2,
    cue: "Arms overhead, palms pressed together, side bend first, then arch back. Keep hips squared forward.",
  },
  {
    name: "Awkward Pose",
    id: "awkward-pose",
    sanskrit: "Utkatasana",
    category: "Standing",
    focus: "Thighs, ankles, core",
    difficulty: "Intermediate",
    hold: 20,
    shape: "chair",
    seq: 3,
    cue: "Knees stack over ankles, thighs work toward parallel to the floor, spine long.",
  },
  {
    name: "Eagle Pose",
    id: "eagle-pose",
    sanskrit: "Garudasana",
    category: "Balance",
    focus: "Ankles, knees, shoulders",
    difficulty: "Intermediate",
    hold: 20,
    shape: "eagle",
    seq: 4,
    cue: "Wrap one leg over the other, opposite arm under, squeeze the wrap and sink the hips.",
  },
  {
    name: "Standing Head to Knee",
    id: "standing-head-to-knee",
    sanskrit: "Dandayamana-Janushirasana",
    category: "Balance",
    focus: "Hamstrings, core, focus",
    difficulty: "Advanced",
    hold: 20,
    shape: "standKneeUp",
    seq: 5,
    cue: "Clasp the foot, extend the leg forward slowly, keep the standing leg locked and spine tall.",
  },
  {
    name: "Standing Bow Pulling Pose",
    id: "standing-bow-pulling",
    sanskrit: "Dandayamana-Dhanurasana",
    category: "Balance",
    focus: "Spine, shoulders, hamstrings",
    difficulty: "Advanced",
    hold: 20,
    shape: "standingBow",
    seq: 6,
    cue: "Kick the back foot into the hand while reaching the front arm forward, chest lifts as the leg rises.",
  },
  {
    name: "Balancing Stick",
    id: "balancing-stick",
    sanskrit: "Tuladandasana",
    category: "Balance",
    focus: "Full body, cardio",
    difficulty: "Advanced",
    hold: 10,
    shape: "balanceStick",
    seq: 7,
    cue: "Fall forward from the hips into a T-shape, arms and back leg parallel to the floor.",
  },
  {
    name: "Standing Separate Leg Stretch",
    id: "standing-separate-leg-stretch",
    sanskrit: "Dandayamana-Bibhaktapada-Paschimotthanasana",
    category: "Forward Fold",
    focus: "Hamstrings, lower back",
    difficulty: "Intermediate",
    hold: 20,
    shape: "straddleFold",
    seq: 8,
    cue: "Wide stance, fold forward from the hips, hands reach back between the ankles.",
  },
  {
    name: "Triangle Pose",
    id: "triangle-pose",
    sanskrit: "Trikonasana",
    category: "Standing",
    focus: "Hips, hamstrings, obliques",
    difficulty: "Intermediate",
    hold: 20,
    shape: "triangle",
    seq: 9,
    cue: "Wide stance, front knee bent to 90°, arms extend in one line, gaze to top hand.",
  },
  {
    name: "Standing Separate Leg Head to Knee",
    id: "standing-separate-leg-head-to-knee",
    sanskrit: "Dandayamana-Bibhaktapada-Janushirasana",
    category: "Forward Fold",
    focus: "Hamstrings, spine",
    difficulty: "Intermediate",
    hold: 20,
    shape: "straddleFold",
    seq: 10,
    cue: "Square the hips to one leg, fold forward, hands frame the foot, forehead reaches toward the shin.",
  },
  {
    name: "Tree Pose",
    id: "tree-pose",
    sanskrit: "Vrikshasana",
    category: "Balance",
    focus: "Ankles, thighs, posture",
    difficulty: "Beginner",
    hold: 20,
    shape: "tree",
    seq: 11,
    cue: "Foot pressed into the inner thigh or calf, avoid the knee, hands at heart or overhead.",
  },
  {
    name: "Toe Stand",
    id: "toe-stand",
    sanskrit: "Padangusthasana",
    category: "Balance",
    focus: "Ankles, knees, core",
    difficulty: "Advanced",
    hold: 20,
    shape: "toeStand",
    seq: 12,
    cue: "From tree, fold forward with a flat back and sit onto the standing heel, lift the bent knee high.",
  },
  {
    name: "Warrior I",
    id: "warrior-i",
    sanskrit: "Virabhadrasana I",
    category: "Standing",
    focus: "Legs, hips, chest",
    difficulty: "Intermediate",
    hold: 20,
    shape: "warrior1",
    cue: "Hips squared to the front, back foot at 45°, front knee over the ankle, arms lift high.",
  },
  {
    name: "Warrior II",
    id: "warrior-ii",
    sanskrit: "Virabhadrasana II",
    category: "Standing",
    focus: "Legs, hips, chest openers",
    difficulty: "Intermediate",
    hold: 20,
    shape: "warrior2",
    cue: "Hips open to the side, front knee bent, arms reach in opposite directions, gaze over front hand.",
  },
  {
    name: "Chair Pose",
    id: "chair-pose",
    sanskrit: "Utkatasana",
    category: "Standing",
    focus: "Thighs, ankles, shoulders",
    difficulty: "Beginner",
    hold: 20,
    shape: "chair",
    cue: "Arms overhead, sit the hips back like an imaginary chair, thighs work, tailbone tucked.",
  },
  {
    name: "Crescent Lunge",
    id: "crescent-lunge",
    sanskrit: "Anjaneyasana",
    category: "Standing",
    focus: "Hips, quadriceps, balance",
    difficulty: "Intermediate",
    hold: 20,
    shape: "lunge",
    cue: "Back knee lowered, front knee stacked, arms lift, sink the front hip back and the back hip forward.",
  },
  {
    name: "Extended Side Angle",
    id: "extended-side-angle",
    sanskrit: "Utthita Parsvakonasana",
    category: "Standing",
    focus: "Obliques, legs, shoulders",
    difficulty: "Intermediate",
    hold: 20,
    shape: "sideAngle",
    cue: "Front knee at 90°, back leg straight, arm reaches forward over the ear or rests on the front knee.",
  },
  {
    name: "Wind Removing Pose",
    id: "wind-removing-pose",
    sanskrit: "Pavanamuktasana",
    category: "Floor",
    focus: "Spine, lower back, digestion",
    difficulty: "Beginner",
    hold: 20,
    shape: "windRemoving",
    seq: 14,
    cue: "Knees hugged tight to the chest, shoulders heavy, rock gently side to side.",
  },
  {
    name: "Sit Up",
    id: "sit-up",
    sanskrit: "—",
    category: "Floor",
    focus: "Core",
    difficulty: "Intermediate",
    hold: 10,
    shape: "sitUp",
    seq: 15,
    cue: "Inhale to sit up with the arms lifted overhead, exhale to lower with control.",
  },
  {
    name: "Cobra Pose",
    id: "cobra-pose",
    sanskrit: "Bhujangasana",
    category: "Backbend",
    focus: "Spine, chest, shoulders",
    difficulty: "Beginner",
    hold: 20,
    shape: "cobra",
    seq: 16,
    cue: "Press the tops of the feet down, chest lifts, shoulders drop away from the ears, elbows slightly bent.",
  },
  {
    name: "Locust Pose",
    id: "locust-pose",
    sanskrit: "Salabhasana",
    category: "Backbend",
    focus: "Lower back, hamstrings",
    difficulty: "Intermediate",
    hold: 20,
    shape: "locust",
    seq: 17,
    cue: "Full prone, lift the chest and legs simultaneously, arms reach back, gaze slightly forward.",
  },
  {
    name: "Full Locust Pose",
    id: "full-locust-pose",
    sanskrit: "Poorna-Salabhasana",
    category: "Backbend",
    focus: "Full back body, glutes",
    difficulty: "Advanced",
    hold: 20,
    shape: "fullLocust",
    seq: 18,
    cue: "Legs and arms lift high, hands interlace behind the back, chest lifts, chin stays off the floor.",
  },
  {
    name: "Toe Stand",
    id: "toe-stand-alt",
    sanskrit: "Padangustasana",
    category: "Balance",
    focus: "Ankles, knees, focus",
    difficulty: "Advanced",
    hold: 15,
    shape: "toeStand",
    seq: 12,
    cue: "Lower onto the toes of one foot from a squat, other foot rests on the thigh.",
  },
  {
    name: "Warrior I",
    id: "warrior-i-alt",
    sanskrit: "Virabhadrasana I",
    category: "Standing",
    focus: "Legs, hips, shoulders",
    difficulty: "Beginner",
    hold: 30,
    shape: "warrior1",
    seq: null,
    cue: "Front knee bent, back leg straight and grounded, arms reach overhead, hips square forward.",
  },
  {
    name: "Warrior II",
    id: "warrior-ii-alt",
    sanskrit: "Virabhadrasana II",
    category: "Standing",
    focus: "Legs, core, shoulders",
    difficulty: "Beginner",
    hold: 30,
    shape: "warrior2",
    seq: null,
    cue: "Front knee bent over ankle, arms extend parallel to the floor, gaze over the front hand.",
  },
  {
    name: "Chair Pose",
    id: "chair-pose-alt",
    sanskrit: "Utkatasana",
    category: "Standing",
    focus: "Legs, glutes, core",
    difficulty: "Beginner",
    hold: 30,
    shape: "chair",
    seq: null,
    cue: "Sit the hips back like lowering onto a chair, weight in the heels, arms reach up.",
  },
  {
    name: "Crescent Lunge",
    id: "crescent-lunge-alt",
    sanskrit: "Anjaneyasana",
    category: "Standing",
    focus: "Hip flexors, balance",
    difficulty: "Intermediate",
    hold: 20,
    shape: "lunge",
    seq: null,
    cue: "Back knee lifted, front knee stacked over ankle, arms reach up and slightly back.",
  },
  {
    name: "Extended Side Angle",
    id: "extended-side-angle-alt",
    sanskrit: "Utthita Parsvakonasana",
    category: "Standing",
    focus: "Hips, side body",
    difficulty: "Intermediate",
    hold: 20,
    shape: "triangle",
    seq: null,
    cue: "Front knee bent deep, forearm to thigh or hand to floor, top arm reaches long overhead.",
  },
  {
    name: "Wind Removing Pose",
    id: "wind-removing-pose-alt",
    sanskrit: "Pavanamuktasana",
    category: "Core",
    focus: "Digestion, lower back",
    difficulty: "Beginner",
    hold: 20,
    shape: "windRemoving",
    seq: 14,
    cue: "Lying down, hug one or both knees to the chest, lower back presses into the floor.",
  },
  {
    name: "Sit-Up",
    id: "sit-up-alt",
    sanskrit: "Pada-Hasthasana transition",
    category: "Core",
    focus: "Abdominals",
    difficulty: "Beginner",
    hold: 10,
    shape: "seatedFold",
    seq: 15,
    cue: "Roll up from lying to seated in one smooth motion, arms sweeping overhead first.",
  },
  {
    name: "Cobra Pose",
    id: "cobra-pose-alt",
    sanskrit: "Bhujangasana",
    category: "Backbend",
    focus: "Spine, chest",
    difficulty: "Beginner",
    hold: 20,
    shape: "cobra",
    seq: 16,
    cue: "Palms under shoulders, lift the chest using back muscles more than the arms, hips stay down.",
  },
  {
    name: "Locust Pose",
    id: "locust-pose-alt",
    sanskrit: "Salabhasana",
    category: "Backbend",
    focus: "Lower back, glutes",
    difficulty: "Intermediate",
    hold: 15,
    shape: "locust",
    seq: 17,
    cue: "Arms alongside the body, lift chest and one or both legs, reaching long through the toes.",
  },
  {
    name: "Full Locust Pose",
    id: "full-locust-pose-alt",
    sanskrit: "Poorna-Salabhasana",
    category: "Backbend",
    focus: "Entire spine",
    difficulty: "Advanced",
    hold: 10,
    shape: "fullLocust",
    seq: 18,
    cue: "Arms extend forward, lift chest, arms and both legs off the floor simultaneously.",
  },
  {
    name: "Bow Pose",
    id: "bow-pose",
    sanskrit: "Dhanurasana",
    category: "Backbend",
    focus: "Full spine, chest, hips",
    difficulty: "Intermediate",
    hold: 20,
    shape: "bow",
    seq: 19,
    cue: "Prone, grab the ankles, lift the chest and thighs simultaneously, gaze forward.",
  },
  {
    name: "Fixed Firm Pose",
    id: "fixed-firm-pose",
    sanskrit: "Supta-Vajrasana",
    category: "Kneeling",
    focus: "Knees, ankles, thighs",
    difficulty: "Advanced",
    hold: 20,
    shape: "fixedFirm",
    seq: 20,
    cue: "Kneel and sit between the feet, knees together, lean back onto the elbows or all the way to the floor.",
  },
  {
    name: "Half Tortoise Pose",
    id: "half-tortoise-pose",
    sanskrit: "Ardha-Kurmasana",
    category: "Kneeling",
    focus: "Shoulders, spine, hips",
    difficulty: "Beginner",
    hold: 20,
    shape: "childs",
    seq: 21,
    cue: "Kneel, fold forward, arms extended overhead on the floor, forehead rests, hips stay over the knees.",
  },
  {
    name: "Camel Pose",
    id: "camel-pose",
    sanskrit: "Ustrasana",
    category: "Backbend",
    focus: "Spine, chest, hip flexors",
    difficulty: "Intermediate",
    hold: 20,
    shape: "camel",
    seq: 22,
    cue: "Kneeling, hands on the lower back or reach for the heels, chest lifts, hips press forward.",
  },
  {
    name: "Rabbit Pose",
    id: "rabbit-pose",
    sanskrit: "Sasangasana",
    category: "Forward Fold",
    focus: "Spine, scalp, neck",
    difficulty: "Intermediate",
    hold: 20,
    shape: "rabbit",
    seq: 23,
    cue: "Kneel, grip the heels, round forward, tuck the chin, roll onto the crown of the head.",
  },
  {
    name: "Head to Knee with Stretching",
    id: "head-to-knee-with-stretching",
    sanskrit: "Janushirasana with Paschimotthanasana",
    category: "Forward Fold",
    focus: "Hamstrings, spine, back",
    difficulty: "Intermediate",
    hold: 20,
    shape: "headToKnee",
    seq: 24,
    cue: "One foot presses into the opposite inner thigh, hinges forward over the extended leg, arms long.",
  },
  {
    name: "Spine Twist",
    id: "spine-twist",
    sanskrit: "Ardha-Matsyendrasana",
    category: "Floor",
    focus: "Spine, obliques, hips",
    difficulty: "Intermediate",
    hold: 20,
    shape: "spineTwist",
    seq: 25,
    cue: "One foot crosses over the opposite thigh, twist toward the bent knee, gaze over the shoulder.",
  },
  {
    name: "Child's Pose",
    id: "childs-pose",
    sanskrit: "Balasana",
    category: "Restorative",
    focus: "Spine, shoulders, relaxation",
    difficulty: "Beginner",
    hold: 30,
    shape: "childs",
    cue: "Knees wide, big toes touching, fold forward, arms extended or resting alongside the body.",
  },
  {
    name: "Cat-Cow",
    id: "cat-cow",
    sanskrit: "Marjaryasana-Bitilasana",
    category: "Floor",
    focus: "Spine mobility, core",
    difficulty: "Beginner",
    hold: 5,
    shape: "catCow",
    cue: "Tabletop position, alternate between arching and rounding the spine with the breath.",
  },
  {
    name: "Downward Dog",
    id: "downward-dog",
    sanskrit: "Adho Mukha Svanasana",
    category: "Inversion",
    focus: "Hamstrings, shoulders, spine",
    difficulty: "Beginner",
    hold: 30,
    shape: "downDog",
    cue: "Lift the hips up and back, heels reach toward the floor, head between the arms, peddle the feet.",
  },
  {
    name: "Upward Dog",
    id: "upward-dog",
    sanskrit: "Urdhva Mukha Svanasana",
    category: "Backbend",
    focus: "Spine, chest, wrists",
    difficulty: "Beginner",
    hold: 15,
    shape: "cobra",
    cue: "Press through the hands, thighs and knees lift off the floor, chest opens, shoulders stack over wrists.",
  },
  {
    name: "Plank",
    id: "plank",
    sanskrit: "Phalakasana",
    category: "Core",
    focus: "Core, arms, shoulders",
    difficulty: "Intermediate",
    hold: 20,
    shape: "plank",
    cue: "Wrists under shoulders, body in a straight line from heels to the crown, core engaged.",
  },
  {
    name: "Chaturanga",
    id: "chaturanga",
    sanskrit: "Chaturanga Dandasana",
    category: "Core",
    focus: "Arms, shoulders, core",
    difficulty: "Advanced",
    hold: 10,
    shape: "plank",
    cue: "From plank, lower to a low push-up with elbows at 90° and hugged close to the ribs.",
  },
  {
    name: "Pigeon Pose",
    id: "pigeon-pose",
    sanskrit: "Eka Pada Rajakapotasana",
    category: "Hip Opener",
    focus: "Hips, glutes, lower back",
    difficulty: "Intermediate",
    hold: 30,
    shape: "pigeon",
    cue: "Front shin angled toward the opposite hip, back leg extended, fold forward or stay upright.",
  },
  {
    name: "Seated Forward Fold",
    id: "seated-forward-fold",
    sanskrit: "Paschimotthanasana",
    category: "Forward Fold",
    focus: "Hamstrings, spine, back",
    difficulty: "Intermediate",
    hold: 30,
    shape: "seatedFold",
    cue: "Sit with legs extended, hinge from the hips, reach for the feet or shins, forehead toward the knees.",
  },
  {
    name: "Bridge Pose",
    id: "bridge-pose",
    sanskrit: "Setu Bandhasana",
    category: "Backbend",
    focus: "Spine, glutes, chest",
    difficulty: "Beginner",
    hold: 20,
    shape: "bridge",
    cue: "Supine, knees bent, feet hip-width apart, press the feet down and lift the hips.",
  },
  {
    name: "Fixed Firm Pose",
    id: "fixed-firm-pose-alt",
    sanskrit: "Supta-Vajrasana",
    category: "Backbend",
    focus: "Quads, ankles, knees",
    difficulty: "Advanced",
    hold: 20,
    shape: "kneelLeanBack",
    seq: 20,
    cue: "Kneeling, sit between the heels, then recline back onto the elbows or floor if flexibility allows.",
  },
  {
    name: "Half Tortoise Pose",
    id: "half-tortoise-pose-alt",
    sanskrit: "Ardha-Kurmasana",
    category: "Forward Fold",
    focus: "Shoulders, spine (rest)",
    difficulty: "Beginner",
    hold: 30,
    shape: "kneelForward",
    seq: 21,
    cue: "Kneeling, fold forward with arms stretched long in front, forehead toward the floor.",
  },
  {
    name: "Camel Pose",
    id: "camel-pose-alt",
    sanskrit: "Ustrasana",
    category: "Backbend",
    focus: "Chest, hip flexors",
    difficulty: "Advanced",
    hold: 20,
    shape: "kneelLeanBack",
    seq: 22,
    cue: "Kneeling, hands to heels, lift the chest up and back, hips press forward over the knees.",
  },
  {
    name: "Rabbit Pose",
    id: "rabbit-pose-alt",
    sanskrit: "Sasangasana",
    category: "Forward Fold",
    focus: "Spine, counter to camel",
    difficulty: "Intermediate",
    hold: 20,
    shape: "kneelForward",
    seq: 23,
    cue: "Forehead tucks toward the knees, hold the heels, round the spine deeply — the counterpose to Camel.",
  },
  {
    name: "Head to Knee with Stretching",
    id: "head-to-knee-with-stretching-alt",
    sanskrit: "Janushirasana-Paschimotthanasana",
    category: "Forward Fold",
    focus: "Hamstrings, spine",
    difficulty: "Intermediate",
    hold: 20,
    shape: "seatedFold",
    seq: 24,
    cue: "One leg extended, fold over it, then switch to both legs extended for the second half.",
  },
  {
    name: "Spine Twist",
    id: "spine-twist-alt",
    sanskrit: "Ardha-Matsyendrasana",
    category: "Twist",
    focus: "Spine mobility, detox",
    difficulty: "Beginner",
    hold: 20,
    shape: "seatedTwist",
    seq: 25,
    cue: "Seated, cross one leg over, twist the torso toward the bent knee, opposite elbow outside it.",
  },
  {
    name: "Child's Pose",
    id: "childs-pose-alt",
    sanskrit: "Balasana",
    category: "Restorative",
    focus: "Lower back, hips (rest)",
    difficulty: "Beginner",
    hold: 40,
    shape: "childs",
    seq: null,
    cue: "Big toes together, knees wide or together, forehead rests down, arms extended or by the sides.",
  },
  {
    name: "Cat-Cow",
    id: "cat-cow-alt",
    sanskrit: "Marjaryasana-Bitilasana",
    category: "Restorative",
    focus: "Spine mobility",
    difficulty: "Beginner",
    hold: 30,
    shape: "catCow",
    seq: null,
    cue: "On all fours, alternate arching and rounding the spine with the breath.",
  },
  {
    name: "Downward Dog",
    id: "downward-dog-alt",
    sanskrit: "Adho Mukha Svanasana",
    category: "Forward Fold",
    focus: "Shoulders, hamstrings, calves",
    difficulty: "Beginner",
    hold: 30,
    shape: "downdog",
    seq: null,
    cue: "Hips lift high and back, heels reach toward the floor, spine stays long.",
  },
  {
    name: "Upward Dog",
    id: "upward-dog-alt",
    sanskrit: "Urdhva Mukha Svanasana",
    category: "Backbend",
    focus: "Spine, chest, shoulders",
    difficulty: "Intermediate",
    hold: 15,
    shape: "updog",
    seq: null,
    cue: "Thighs lift off the floor, chest opens forward and up, shoulders stay away from the ears.",
  },
  {
    name: "Plank",
    id: "plank-alt",
    sanskrit: "Phalakasana",
    category: "Core",
    focus: "Core, shoulders, back",
    difficulty: "Beginner",
    hold: 30,
    shape: "plank",
    seq: null,
    cue: "Straight line from head to heels, core braced, shoulders stacked over wrists.",
  },
  {
    name: "Chaturanga",
    id: "chaturanga-alt",
    sanskrit: "Chaturanga Dandasana",
    category: "Core",
    focus: "Core, arms, chest",
    difficulty: "Intermediate",
    hold: 10,
    shape: "chaturanga",
    seq: null,
    cue: "Lower halfway, elbows tracking close to the ribs, forearms stay vertical.",
  },
  {
    name: "Pigeon Pose",
    id: "pigeon-pose-alt",
    sanskrit: "Eka Pada Rajakapotasana",
    category: "Hip Opener",
    focus: "Hips, glutes",
    difficulty: "Intermediate",
    hold: 30,
    shape: "pigeon",
    seq: null,
    cue: "Front shin angles forward, back leg extends long behind, fold forward for more release.",
  },
  {
    name: "Seated Forward Fold",
    id: "seated-forward-fold-alt",
    sanskrit: "Paschimottanasana",
    category: "Forward Fold",
    focus: "Hamstrings, lower back",
    difficulty: "Beginner",
    hold: 30,
    shape: "seatedFold",
    seq: null,
    cue: "Legs extended, hinge from the hips rather than rounding the back, reach for the feet or shins.",
  },
  {
    name: "Bridge Pose",
    id: "bridge-pose-alt",
    sanskrit: "Setu Bandhasana",
    category: "Backbend",
    focus: "Glutes, spine, chest",
    difficulty: "Beginner",
    hold: 20,
    shape: "bridge",
    seq: null,
    cue: "Feet hip-width, press into the heels to lift the hips, hands can clasp underneath.",
  },
  {
    name: "Wheel Pose",
    id: "wheel-pose",
    sanskrit: "Urdhva Dhanurasana",
    category: "Backbend",
    focus: "Full spine, chest, shoulders",
    difficulty: "Advanced",
    hold: 20,
    shape: "wheel",
    cue: "Supine, hands by the ears, press into a full backbend, arms and legs straight, chest open.",
  },
  {
    name: "Fish Pose",
    id: "fish-pose",
    sanskrit: "Matsyasana",
    category: "Backbend",
    focus: "Upper back, throat, chest",
    difficulty: "Intermediate",
    hold: 20,
    shape: "fish",
    cue: "Supine, forearms press to lift the chest, crown of the head rests lightly, legs engaged.",
  },
  {
    name: "Butterfly",
    id: "butterfly",
    sanskrit: "Baddha Konasana",
    category: "Hip Opener",
    focus: "Hips, inner thighs",
    difficulty: "Beginner",
    hold: 30,
    shape: "butterfly",
    cue: "Soles of the feet together, knees open wide, hold the feet and gently press the knees down.",
  },
  {
    name: "Reclining Twist",
    id: "reclining-twist",
    sanskrit: "Supta Matsyendrasana",
    category: "Floor",
    focus: "Spine, obliques, hips",
    difficulty: "Beginner",
    hold: 30,
    shape: "recliningTwist",
    cue: "Supine, one knee crosses over the opposite side, arms in a T, gaze toward the bent knee.",
  },
  {
    name: "Happy Baby",
    id: "happy-baby",
    sanskrit: "Ananda Balasana",
    category: "Hip Opener",
    focus: "Hips, lower back, hamstrings",
    difficulty: "Beginner",
    hold: 20,
    shape: "happyBaby",
    cue: "Supine, grab the outer edges of the feet, knees wide toward the armpits, rock gently.",
  },
  {
    name: "Side Plank",
    id: "side-plank",
    sanskrit: "Vasisthasana",
    category: "Core",
    focus: "Obliques, arms, balance",
    difficulty: "Advanced",
    hold: 20,
    shape: "sidePlank",
    cue: "From plank, shift weight to one hand and the outer edge of the same foot, stack the top foot, top arm lifts.",
  },
  {
    name: "Corpse Pose",
    id: "corpse-pose",
    sanskrit: "Savasana",
    category: "Restorative",
    focus: "Relaxation, integration",
    difficulty: "Beginner",
    hold: 120,
    shape: "corpse",
    seq: 13,
    cue: "Lie flat on the back, arms at the sides palms up, legs relaxed, eyes closed. Breathe naturally.",
  },
  {
    name: "Blowing in Firm Pose",
    id: "blowing-in-firm-pose",
    sanskrit: "—",
    category: "Floor",
    focus: "Core, breath control",
    difficulty: "Intermediate",
    hold: 10,
    shape: "spineTwist",
    seq: 26,
    cue: "A forceful exhale from the belly, knees hugged to the chest, rounds the upper back on the exhale.",
  },
  {
    name: "Fish Pose",
    id: "fish-pose-alt",
    sanskrit: "Matsyasana",
    category: "Backbend",
    focus: "Chest, throat, upper back",
    difficulty: "Intermediate",
    hold: 20,
    shape: "fish",
    seq: null,
    cue: "Lying down, arch the upper back, crown of the head rests lightly on the floor, chest opens.",
  },
  {
    name: "Butterfly Pose",
    id: "butterfly-pose-alt",
    sanskrit: "Baddha Konasana",
    category: "Hip Opener",
    focus: "Inner thighs, hips",
    difficulty: "Beginner",
    hold: 30,
    shape: "butterfly",
    seq: null,
    cue: "Soles of the feet together, knees release toward the floor, spine stays long.",
  },
  {
    name: "Reclining Twist",
    id: "reclining-twist-alt",
    sanskrit: "Supta Matsyendrasana",
    category: "Twist",
    focus: "Spine, lower back release",
    difficulty: "Beginner",
    hold: 30,
    shape: "recliningTwist",
    seq: null,
    cue: "Lying down, knees drop to one side while shoulders stay grounded, gaze the opposite way.",
  },
  {
    name: "Happy Baby",
    id: "happy-baby-alt",
    sanskrit: "Ananda Balasana",
    category: "Restorative",
    focus: "Hips, lower back release",
    difficulty: "Beginner",
    hold: 30,
    shape: "happyBaby",
    seq: null,
    cue: "Lying down, grab the outer edges of the feet, knees draw toward the armpits.",
  },
  {
    name: "Side Plank",
    id: "side-plank-alt",
    sanskrit: "Vasisthasana",
    category: "Core",
    focus: "Obliques, shoulders",
    difficulty: "Intermediate",
    hold: 20,
    shape: "sidePlank",
    seq: null,
    cue: "Stack the feet, lift the hips high, top arm reaches to the sky.",
  },
  {
    name: "Corpse Pose",
    id: "corpse-pose-alt",
    sanskrit: "Savasana",
    category: "Restorative",
    focus: "Full body integration",
    difficulty: "Beginner",
    hold: 60,
    shape: "corpse",
    seq: 13,
    cue: "Lie flat, palms up, let the whole body go heavy — this is where the practice absorbs.",
  },
  {
    name: "Blowing in Firm Pose",
    id: "blowing-in-firm-pose-alt",
    sanskrit: "Kapalbhati Pranayama",
    category: "Restorative",
    focus: "Breath, final release",
    difficulty: "Beginner",
    hold: 30,
    shape: "kneelLeanBack",
    seq: 26,
    cue: "Kneeling, seated on the heels, forceful exhales through the nose to finish the practice.",
  },
  {
    name: "Mountain Pose",
    id: "mountain-pose",
    sanskrit: "Tadasana",
    category: "Standing",
    focus: "Posture, alignment, grounding",
    difficulty: "Beginner",
    hold: 30,
    shape: "standing",
    cue: "Stand tall with feet together or hip-width, arms at sides, engage the thighs, lengthen the spine, crown of the head reaches up.",
  },
  {
    name: "Forward Fold",
    id: "forward-fold",
    sanskrit: "Uttanasana",
    category: "Forward Fold",
    focus: "Hamstrings, spine, release",
    difficulty: "Beginner",
    hold: 30,
    shape: "forwardFold",
    cue: "Hinge forward from the hips, knees soft, let the head and neck hang heavy, palms flat or hold the elbows.",
  },
  {
    name: "Half Forward Fold",
    id: "half-forward-fold",
    sanskrit: "Ardha Uttanasana",
    category: "Forward Fold",
    focus: "Spine, chest opener",
    difficulty: "Beginner",
    hold: 20,
    shape: "forwardFold",
    cue: "From a forward fold, lift the chest halfway, flat back, fingertips or palms on the floor or shins.",
  },
  {
    name: "Reverse Warrior",
    id: "reverse-warrior",
    sanskrit: "Viparita Virabhadrasana",
    category: "Standing",
    focus: "Obliques, legs, chest opener",
    difficulty: "Intermediate",
    hold: 20,
    shape: "reverseWarrior",
    cue: "From Warrior II, front knee bent, back arm slides down the back leg, front arm reaches overhead, gentle side bend.",
  },
  {
    name: "Shoulder Stand",
    id: "shoulder-stand",
    sanskrit: "Sarvangasana",
    category: "Inversion",
    focus: "Thyroid, shoulders, spine",
    difficulty: "Advanced",
    hold: 60,
    shape: "shoulderStand",
    cue: "Lie supine, lift the legs and hips overhead, hands support the lower back, legs straight up, chin tucked.",
  },
  {
    name: "Plow Pose",
    id: "plow-pose",
    sanskrit: "Halasana",
    category: "Inversion",
    focus: "Spine, shoulders, hamstrings",
    difficulty: "Advanced",
    hold: 60,
    shape: "plowPose",
    cue: "From shoulder stand, lower the feet overhead toward the floor, hands support the back or interlace on the floor.",
  },
];

export const YOGA_FLOWS = {
  hot26: {
    id: "hot26",
    name: "Hot Yoga — 26 Postures",
    desc: "The classic Bikram-inspired 26-posture sequence in a heated room.",
    poseIds: [
      "standing-deep-breathing",
      "half-moon",
      "awkward-pose",
      "eagle-pose",
      "standing-head-to-knee",
      "standing-bow-pulling",
      "balancing-stick",
      "standing-separate-leg-stretch",
      "triangle-pose",
      "standing-separate-leg-head-to-knee",
      "tree-pose",
      "toe-stand",
      "corpse-pose",
      "wind-removing-pose",
      "sit-up",
      "cobra-pose",
      "locust-pose",
      "full-locust-pose",
      "bow-pose",
      "fixed-firm-pose",
      "half-tortoise-pose",
      "camel-pose",
      "rabbit-pose",
      "head-to-knee-with-stretching",
      "spine-twist",
      "blowing-in-firm-pose",
    ],
  },
  vinyasa: {
    id: "vinyasa",
    name: "Vinyasa Flow",
    desc: "A fluid breath-linked sequence — sun salutations, standing poses, hip openers, and a calm finish.",
    poseIds: [
      "mountain-pose",
      "standing-deep-breathing",
      "half-moon",
      "forward-fold",
      "half-forward-fold",
      "downward-dog",
      "chaturanga",
      "upward-dog",
      "downward-dog",
      "half-forward-fold",
      "forward-fold",
      "mountain-pose",
      "warrior-i",
      "warrior-ii",
      "reverse-warrior",
      "warrior-ii",
      "warrior-i",
      "forward-fold",
      "half-forward-fold",
      "downward-dog",
      "chaturanga",
      "upward-dog",
      "downward-dog",
      "half-forward-fold",
      "forward-fold",
      "mountain-pose",
      "tree-pose",
      "eagle-pose",
      "triangle-pose",
      "extended-side-angle",
      "pigeon-pose",
      "seated-forward-fold",
      "butterfly",
      "bridge-pose",
      "wheel-pose",
      "shoulder-stand",
      "plow-pose",
      "cobra-pose",
      "locust-pose",
      "bow-pose",
      "childs-pose",
      "seated-forward-fold",
      "spine-twist",
      "corpse-pose",
    ],
  },
} as const;

export function exById(exercises: Exercise[], id: string): Exercise | undefined {
  return exercises.find((e) => e.id === id);
}

export function activeProgram(
  programs: Program[],
  activeProgramId: string | null,
): Program | undefined {
  return programs.find((p) => p.id === activeProgramId);
}

export function todayKey(): string {
  return new Date().toISOString().slice(0, 10);
}
